name: production-deploy

# Trigger the workflow on push or pull request events on the production branch

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
# authenticate to the server via ssh and run our deployment script to deploy the app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: "./.scripts/deploy.sh"
