name: Deploy to Ubuntu

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 'dd'
                uses: actions/checkout@v2

            - name:  
                uses: webfactory/ssh-agent@v0.5.1
                with:
                    ssh-private-key: ${{ secrets.SSH_KEY }}

            - name:
                run: |
                    sudo apt-get update
                    sudo apt-get install -y php composer

            - name:  
                run: |
                    composer install --no-dev --optimize-autoloader
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache
                    php artisan migrate --force
                    php artisan optimize 